export const imageRoot = 'https://image.tmdb.org/t/p/original/';
export const urlRoot = 'http://localhost:5000';
export const emailRegex = /^(([^<>()[\]\.,;:\s@\']+(\.[^<>()[\]\.,;:\s@\']+)*)|(\'.+\'))@(([^<>()[\]\.,;:\s@\']+\.)+[^<>()[\]\.,;:\s@\']{2,})$/i;
export const Genres = {
Action : 'Action',
Anime : 'Anime',
Documental : 'Documentales',
Drama : 'Drama',
Espionage : 'Espionage',
Family : 'Family',
Fantasy : 'Fantasy',
Food : 'Food',
History : 'History',
Horror : 'Horror',
Legal : 'Legal',
Medical : 'Medical',
Music : 'Music',
Mystery : 'Mystery',
Nature : 'Nature',
Romance : 'Romance',
ScienceFiction : 'Science-Fiction',
Sports : 'Sports',
Supernatural : 'Supernatural',
Thriller : 'Thriller',
Travel : 'Travel',
War : 'War',
Western : 'Western',
Original : 'Original',
Comedy: 'Comedy',
}
